[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "h-emcee"
version = "0.0.0"
description = "Affine invariant Hamiltonian samplers in JAX"
authors = [{name = "Clark Miyamoto"}]
readme = "README.md"
requires-python = ">=3.9"
dependencies = ["jax", "jaxlib"]

[tool.setuptools.packages.find]
where = ["src"]
